name: pytest
on:
    workflow_dispatch:
    pull_request:
        paths:
            - "src/**"
            - "tests/**"
            - "pyproject.toml"

permissions:
    contents: write
    pull-requests: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version-file: "pyproject.toml"

            - name: Install uv
              uses: astral-sh/setup-uv@v7
              with:
                  enable-cache: true
                  version: 0.*.*

            - name: Install dependencies
              run: uv sync --locked

            - name: Run tests (with coverage)
              run: |
                  uv run pytest \
                    --junitxml=pytest.xml \
                    --cov-report=term-missing:skip-covered \
                    --cov=. \
                    | tee pytest-coverage.txt

            - name: Pytest coverage comment
              uses: MishaKav/pytest-coverage-comment@main
              with:
                  pytest-coverage-path: ./pytest-coverage.txt
                  junitxml-path: ./pytest.xml
